### ISSUE TITLE
Can we add a table of contents to our HTML reports? (i.e. based on headers)

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/subreport#20]

**Comment by joethorley** [comment]
cool idea - could there be a hyperlink down?

**Comment by sebdalgarno** [comment]
this can actually be done from poisreport - see PR May 26

**Comment by joethorley** [comment]
Closing as dealt with here https://github.com/poissonconsulting/poisreport/pull/16#pullrequestreview-1448379585
